### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by djreyes** [djreyes/todo#2]
/cc @timothy1ee - You mentioned liking a setter/getter pattern for the custom cell but I wasn't sure how to implement it. So I tried this way. It feels a bit hacky and I know there is a bug that makes it crash when you try to add an item while the keyboard is still in view. I couldn't figure that out but everything else should work.

**Comment by timothy1ee** [comment]
Good work, much better.  The next level is to be able to implement the multi-line to do item.  It's an illustration of what it takes to really fine tune a UI.  It's an intermediate level task.  Not incredibly difficult, but may take you as long as the rest of the assignment.
- Note: there is a convenient method on NSMutableArray called `exchangeObjectAtIndex:withObjectAtIndex:`
- Upon adding a new item, it would be nice to automatically set the focus to the new text field.
- It's common to dismiss the keyboard on scroll.
- Good work finding the `editButtonItem` that automatically tracks the states of the editing state of the UIViewController. 

Here's my checklist of things I'm looking at when I'm reviewing this project.
- Is the Objective-C code styling consistent with standards?
- Did you create a custom cell or use tableview prototypes? Either approach is fine.
- In your custom cell, did you configure the Auto Layout properties?  Or, if you didn't use AutoLayout, did you set the autoresizingMask to UIViewAutoresizingFlexibleHeight | UIViewAutoresizingFlexibleWidth.
- How did you sync the UITextField changes with the underlying array of todo items?  There are many options:
  - Set the view controller to be the delegate of each UITextField. Track the index of the UITextField using the tag property or objc_getAssociatedObject/objc_setAssociatedObject.
  - Set the cell to be the delegate of the UITextField and create a custom cell delegate.
- How was persistence implemented?
  - NSUserDefaults
  - File system
